# Windows build. The old Dev-C++ file pointed at C:/Dev-Cpp, which is not
# present on a normal machine. This forwards to the top-level Makefile,
# which links MinGW freeglut and OpenAL.
OS := Windows_NT
include Makefile
